### PR TITLE
ADDED: [Feature] GitHub Repository Tracking

### LINKED ISSUE #99: [Feature] GitHub repository tracking
## Description
The project could track the number of repositories on GitHub that use creative commons licenses.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by IamMQaisar**
## Fixes

Fixes #99 by @Darylgolden
- #99 

## Description

Added `github_scratcher.py` to now track the total number of repositories on GitHub that utilize Creative Commons licenses of all types.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Darylgolden** [comment]
Hey @IamMQaisar, I'm not sure if you missed it but I've already started working on a PR fixing this at #101. Sorry that it's taking a while for me to respond to the reviews as I'm busy with other things IRL.

**Comment by IamMQaisar** [comment]
Hi @Darylgolden ,
   Yes Brother, I know that you are working on the PR and this PR of mine was just to fast track and ommit the errors as well as to correlate with the latest changes of the codebase mergers.

You may eventually **bring out the changes of files, from my PR to your and make your PR better/complete** so that @TimidRobot has ease in merging the PR rather than us being waiting that he mentions all the changes himself and then we make those changes. Which will only delay the process and make the maintainer go through and mention everything manually.

**Comment by Darylgolden** [comment]
I understand, but I think it would have been better if you had made a PR to my branch if you wanted to help fix the issues in my PR. Creating a competing PR makes the attribution of changes unclear and feels like it creates a sense of competition rather than collaboration, even if that was not your intention. Also, for a open source project, I don't think a 3 day wait from a review is that long to necessitate superseding another PR. I would have understood if it was stale for a week or longer.

**Comment by IamMQaisar** [comment]
Sure, I'll take that into account and make it more collaborative next time by doing a PR into the existing PR of others.

**Comment by IamMQaisar** [comment]
> I understand, but I think it would have been better if you had made a PR to my branch if you wanted to help fix the issues in my PR. 

I am unable to fork your repo, as it's probably not enabled to be forked. Can you enable it so that I can fork and work on it?

**Comment by Darylgolden** [comment]
@IamMQaisar I believe it's enabled by default. What problems do you get when you attempt to fork?

**Comment by IamMQaisar** [comment]
Let me show you in a while.

**Comment by IamMQaisar** [comment]
image

**Review by artemdoneu-cmd — COMMENTED** [review]
5ннр

**Pull request closed without merging**
